[users]
andre = "1234"
leonardo = "1508"
cliente = "4321"

# Usuários do sistema
[usuarios]

[usuarios.admin]
senha = "2025"
nome_completo = "Administrador"

[usuarios.rodrigo]
senha = "2025"
nome_completo = "Rodrigo Capistrano"

[usuarios.victor]
senha = "2025"
nome_completo = "Victor"

[usuarios.claudia]
senha = "2025"
nome_completo = "Claudia"

[usuarios.leonardo]
senha = "leo123"
nome_completo = "José Leonardo"

[usuarios.secretaria]
senha = "sec2025"
nome_completo = "Secretaria"

[github]
repo_owner = "leoparipiranga"
repo_name = "capistrano"
token = "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"

[api]
token = "A92FD-7C4BAE1F3C9-82E"
url_processos = "https://apisp.fabricadetempo.cloud/webhook/korbil/capistrano/processos"
url_clientes = "https://apisp.fabricadetempo.cloud/webhook/korbil/capistrano/clientes"
url_tarefas = "https://apisp.fabricadetempo.cloud/webhook/korbil/capistrano/tarefas?dataInicio=2020-01-01&dataFim=2025-12-31"





